archi/urls.py
# -*- coding: utf8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from website.views import *
#from website.sitemap import *
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import ChantierSitemap, MediaSitemap,  StaticViewSitemap
 

sitemaps = { 'chantiers': ChantierSitemap, 'medias':MediaSitemap, 'static': StaticViewSitemap,}


urlpatterns = patterns('', 
    
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$' ,'website.views.index4', name='index'),
    
    url(r'^profil/$' ,Profil.as_view(), name='profil'),
    url(r'^profile/$', ProfileDetail.as_view(), name='profile-view', ),
    # url(r'^projets/$' ,'website.views.index_chantier_selection', name='index'),
    url(r'^projets/$' ,'website.views.index_projets', name='index'),
    # url(r'^projets/(?P<code_projet>\w+)/$' ,'website.views.index_chantier_selection', name='index_chantier_selection'),
    url(r'^projet/(?P<pk2>\w+)/$', ProjetcDetail.as_view(), name='projet-view', ),    

    url(r'^artsetartisanats/$', 'website.views.index_ArtsArtisanat', name='media-view', ),
    url(r'^artsetartisanats/(?P<code_projet>\w+)/$' ,'website.views.index_media_selection', name='index_media_selection'),
    url(r'^artsetartisanat/(?P<pk3>\w+)/$', MediaDetail.as_view(), name='media-view-detail', ),

    url(r'^images/(?P<pk>\d+)/$', ImageView.as_view(), name='image-view',),

    url(r'^contact/$', 'website.views.contact', name='contact',),
    url(r'^tinymce/', include('tinymce.urls')),

    (r'^sitemap\.xml', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

 

    
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# sitemaps = {
#  'Chantier':ChantierSitemap,
#  'site':Sitemap(['name_of_url', 'name_of_url']),
# }

website/urls.py
# -*- coding: utf8 -*-
#from django.conf.urls.defaults import *
from django.conf.urls import patterns, include, url
from website.models import Item, Photo
from django.views.generic import TemplateView


urlpatterns = patterns ('', 
    (r'^$', TemplateView.as_view(template_name="index.html", 
    	
    	kwargs={ 
    	     	'extra_context': {'item_list': lambda: Item.objects.all()},
        	},
	

	))  +  patterns('django.views.generic',




	url(r'^$', 'simple.direct_to_template',
		
		kwargs={
			'template': 'index.html',
			'extra_context': {'item_list': lambda: Item.objects.all()}
		},
		
		name='index'
	),

	url(r'^items/$', 'list_detail.object_list',
	 	
	 	kwargs={
			'queryset': Item.objects.all(),
		 	'template_name': 'items_list.html',
			'allow_empty': True,
		},
		
		name='item_list'
	),
	
	url(r'^items/(?P<object_id>\d+)/$', 'list_detail.object_detail',
		
		kwargs={
			'queryset': Item.objects.all(),
			'template_name': 'items_detail.html'
		},
		
		name='item_detail'
		
	),
	
	url(r'^photos/(?P<object_id>\d+)/$', 'list_detail.object_detail',
		
		kwargs={
			'queryset': Photo.objects.all(),
			'template_name': 'photos_detail.html'
		},
		
		name='photo_detail'
	),

	url(r'^detail/(?P<pk>\d+)/$', contacts.views.ChantierView.as_view(),
		name='chantier-view',),


)

website/models.py
# -*- coding: utf8 -*- 
from django.db import models  
from django.contrib.contenttypes.admin import GenericTabularInline
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from fields import ThumbnailImageField
from django.core.urlresolvers import reverse
from django.forms import ModelForm
from django.conf import settings
from tinymce.models import HTMLField
 
"""
def get_aticle_default():
    return Article.objects.get(id=1)
"""

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = ThumbnailImageField(upload_to='', blank=True)
    content = HTMLField()
    
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

    def __unicode__(self):
        return 'Profile for user {}'.format(self.user.username)

class Image(models.Model):
    AFFI_PAGE_ACCUEIL = (
        ('oui', 'Afficher dans la page Home'),
        ('non', 'Ne pas l afficher dans la page Home'),
    )
    
    title = models.CharField(max_length=100)
    photo =  ThumbnailImageField(upload_to='')
    caption = models.CharField(max_length=250, blank=True)
    afficher = models.CharField(max_length=3, choices=AFFI_PAGE_ACCUEIL, default='oui')

    class Meta:
        ordering = ['title']

    def affiche(self):
        return self.afficher == 'oui'

    def get_chantier(self):
        return  ImagesDe.objects.filter(image=self)[0].chantier

    def get_media(self):
        return ImagesDe.objects.filter(image=self)[0].media

    
    def __unicode__(self):
        return self.title

    def get__absolute_url(self):        
        return str(self.photo)

    def get_url(self):
        return "/images/"  + str(self.id) 

    def get_images_media(self):
        return Image.objects.filter(media=self)  

    def get_thumb(self):        
        return str(self.photo).replace('.jpg' , '.thumb.jpg')

# Projet 
class Chantier(models.Model): 
    NIVEAU1 = (

        ('ARCHITE', 'Architecture'),
        ('AMEURBA', 'Aménagement'),
        ('DESIGN', 'Design'),
        ('URBAPAY', 'Urbanisme et paysages'),

    )
    
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)   
    date = models.DateField()
    text = models.TextField(max_length=500)
    images = models.ManyToManyField(Image, through='ImagesDe', blank=True, null=True)
    niveau1 = models.CharField(max_length=7, choices=NIVEAU1, default='ARCHITE')

    def get_absolute_url(self):
        return reverse('projet-view', kwargs={'pk2': self.pk})

    def get_niveaux(self):
        return self.NIVEAU1
    
    def get_images_chantier(self):
        return Image.objects.filter(chantier=self)  
    
    def get_niveau(self):
        return self.niveau1 

    def get_niveau_v(self):
        for k in self.NIVEAU1:
            if(k[0]==self.niveau1):
                return k[1]
        return self.niveau1 

    def get_resume(self):
        return self.text     
    class Meta:
        verbose_name = "Projet"
        verbose_name_plural = "Projets"

    def __unicode__(self):
        return self.title   

# Art et Artisanat
class Media(models.Model):
   
    
    NIVEAU1 = (
        ('EXPO', 'Exposition'),
        ('PUBLI', 'Publications'),
        ('ARTICL', 'Articles'),
    )

    title = models.CharField(max_length=250)
    date = models.DateField()
    text = models.TextField(max_length=500)
    images = models.ManyToManyField(Image, through='ImagesDe', blank=True, null=True)
    niveau1 = models.CharField(max_length=7, choices=NIVEAU1, default='ARTICL')

    class Meta:
        verbose_name = "Arts et Artisanat"
        verbose_name_plural = "Arts et Artisanat"

    def get_images_media(self):
        return Image.objects.filter(media=self) 

    def get_niveaux(self):
        return self.NIVEAU1

    def get_niveau(self):
        return self.niveau1

    def get_niveau_v(self):
        for k in self.NIVEAU1:
            if(k[0]==self.niveau1):
                return k[1]
        return self.niveau1 

    def get_resume(self):
        return self.text 
    
    def get_absolute_url(self):
        return reverse('media-view-detail', kwargs={'pk3': self.pk})

    def __unicode__(self):
        return self.title 
        
  

# Relation image / projet  ou art et artisanat
class ImagesDe(models.Model):
    image = models.ForeignKey(Image, blank=True)
    chantier = models.ForeignKey(Chantier, blank=True, null=True)
    media = models.ForeignKey(Media, blank=True, null=True)
    def __unicode__(self):
        if self.chantier :
            return "Photo : " + self.image.title + " du chantier : " + self.chantier.title
  
        if self.media :
            return "Photo : " + self.image.title + " du media : " + self.media.title    




#class non utilisee
class Contact(models.Model):
    nameField = models.CharField(max_length=255)
    firstNameField = models.CharField(max_length=255)
    descField = models.TextField(max_length=500)
    phoneField = models.CharField(max_length=14, default='')
    emailField = models.EmailField()
    def __unicode__(self):
        return    (str(self.nameField)).upper() + "  " +  str(self.firstNameField)





"""
contact non utilisee
"""

@admin.register(Contact)
class ContactAdmin(admin.ModelAdmin):
   pass  


@admin.register(Image)
class ImageAdmin(admin.ModelAdmin):
    list_display = ('title', 'photo', 'caption', 'afficher')
    search_fields = ('title',)


class ImagesInline(admin.TabularInline):
    model = Chantier.images.through


class ImageInline(admin.ModelAdmin):
    inlines = [
        ImagesInline,
    ]

       
@admin.register(Chantier)
class ChantierAdmin(admin.ModelAdmin):
    inlines = [
        ImagesInline,
    ]
    exclude = ('produit', 'media', )


@admin.register(Media)
class MediaAdmin(admin.ModelAdmin):
    inlines = [
        ImagesInline,
    ]


@admin.register(Profile)
class ProfileAdmin(admin.ModelAdmin):
    list_display = ('user','date_of_birth', 'photo', 'content',)

website/forms.py
# -*- coding: utf8 -*-
from django import forms

from django.core.exceptions import ValidationError
from website.models import Contact
from localflavor.fr.forms import FRPhoneNumberField
from django.core.validators import validate_email
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS



class Contact2Form(ModelForm):
    
    def clean(self):
    	    cleaned_data = super(Contact2Form, self).clean()
    	    nameField = cleaned_data.get("nameField")
    	    firstNameField = cleaned_data.get("firstNameField")
    	    emailField = cleaned_data.get("emailField")
    	    phoneField = cleaned_data.get("phoneField")
    	    descField = cleaned_data.get("descField")

            if not nameField or len(nameField) < 2:
                msg_nameField = u"le nom doit contenir plus de 2 caracteres"
                self.add_error('nameField', msg_nameField)
        

            if not firstNameField or len(firstNameField) < 5:
                msg_firstNameField = u"le prenom doit contenir plus de 5 caracteres"
                self.add_error('firstNameField', msg_firstNameField)



            if not emailField or not '@' in emailField:    
                msg_emailField = u"le mail doit contenir @"
                self.add_error('emailField', msg_emailField)


            if not descField or len(descField) < 5:
                msg_descField = u"la descrition doit contenir plus de 5 caracteres"
                self.add_error('descField', msg_descField)

            if not phoneField or len(phoneField) < 10 :
                msg_phoneField = u"le numero de telephone doit contenir plus de 10 caracteres"
                self.add_error('phoneField', msg_phoneField)                

            

        
        
            return cleaned_data
    class Meta:
        model = Contact
        fields = ['nameField', 'firstNameField', 'descField', 'phoneField' ,   'emailField']
        error_messages = {

            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

        



TOPIC_CHOICES = (
    ('general', 'General enquiry'),
    ('bug', 'Bug report'),
    ('suggestion', 'Suggestion'),
)


class ContactFeedForm(forms.Form):
    topic = forms.ChoiceField(choices=TOPIC_CHOICES)
    message = forms.CharField(widget=forms.Textarea())
    sender = forms.EmailField(required=False)
    
    def clean(self):
    	cleaned_data = super(ContactFeedForm, self).clean()
    	message = cleaned_data.get("message")
    	sender = cleaned_data.get("sender")
    	topic = cleaned_data.get("topic")

        if message and sender and topic:
            msg1 = u"Must put 1"
            msg2 = u"Must put 'help' 2"
            msg3 = u"Must put 'help' 3"
            self.add_error('message', msg1)
            self.add_error('sender', msg2)
            self.add_error('topic', msg3)

        return cleaned_data






class ContactForm(forms.Form):
    nameField = forms.CharField(label='Your nom', max_length=100)
    firstNameField = forms.CharField(label='Your prenom', max_length=100)
    emailField = forms.EmailField(required=True, validators=[validate_email])
    phoneField = FRPhoneNumberField()
    descField = forms.CharField(widget=forms.Textarea())
    def clean(self):
    	cleaned_data = super(ContactForm, self).clean()
    	nameField = cleaned_data.get("nameField")
    	firstNameField = cleaned_data.get("firstNameField")
    	emailField = cleaned_data.get("emailField")
    	phoneField = cleaned_data.get("phoneField")
    	descField = cleaned_data.get("descField")
        if len(nameField) < 5:
            msg_nameField = u"le nom doit contenir plus de 2 caracteres"
            self.add_error('nameField', msg_nameField)
        if len(firstNameField) < 5:
            msg_firstNameField = u"le prenom doit contenir plus de 2 caracteres"
            self.add_error('firstNameField', msg_firstNameField)
        if not '@' in emailField:    
            msg_emailField = u"le mail doit contenir @"
            self.add_error('emailField', msg_emailField)
        return cleaned_data

website/templates/base.html
<!DOCTYPE html>
<html>

	<head>

	
		<title>Gallery - {% block title %}{% endblock %}</title>
		
		<style type="text/css">
			body {vertical-align: top; margin: 30px; font-family: sans-serif; background: #fff; }
			h1 { background: #ccf; padding: 20px; }
			h2 { background: #ddf; padding: 10px 20px; }
			h3 { background: #eef; padding: 5px 20px; }
			
			table { width: 100%; }
			table th { text-align: right; }
			tbody tr { display: table-cell; vertical-align: top; }
			img.photo_mosaique { width: 150px;  }
		
		</style>


	</head>
	


	<body>
		<h1>Gallery</h1>
		{% block content %}{% endblock %}
	</body>



</html>

website/templates/chantier_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}


<h1>{{ chantier.title }}</h1>
<p>Title: {{ chantier }}</p>
<a href="{{ chantier.get_absolute_url }}">{{ chantier.title }}</a>
<p>Photos: {{ chantier.get_images_chantier }}</p>


<ul>
    {% for image in chantier.get_images_chantier  %}
    <br>
    <a href="{{ image.get_url }}"> immage : {{ image.title }}</a>
    <br>
    <img class='photo_mosaique'  src="{% static image.photo%}"/>
    {% empty %}
    <li>No images</li>
    {% endfor %}
</ul>





{% endblock %}

website/templates/contact2.html
{% extends "base4.html" %}

{% load staticfiles %}

{% block title %}Architect{% endblock %}

{% block content %}

{% include "menu.html" %}
<div class="container-fluid"> 

<div class="row">

    




        <div class="col-sm-6 col-md-3 col-lg-3">

                       <p>  
                            TALLUNT PARIS
                            <br>
                            4 rue Pasteur
                            <br>
                            75011 Paris
                            <br>
                            tel fr: +33(0)6 95 55 78 01
                            <br>

                            fax: +33 (0) 9 52 34 34 32
                       </p>


                        <p class="adresse_mail">
                           <a href="mailto:contact@alounasarchitecture.com" rel="nofollow">contact@alounasarchitecture.com</a>
                        </p>
                        </br>  
                     

        </div>


        <div class="col-sm-6 col-md-3 col-lg-3">

                       <p>  
                            TALLUNT ALGER
                            <br>
                            4 rue Pasteur
                            <br>
                            75011 Paris
                            <br>
                            tel alg: +213 552 219 876
                            <br>
                            fax: +33 (0) 9 52 34 34 32
                       </p>


                        <p class="adresse_mail">
                           <a href="mailto:contact@alounasarchitecture.com" rel="nofollow">contact@alounasarchitecture.com</a>
                        </p>
                        </br>  
                     

        </div>

                <div class="col-sm-6 col-md-3 col-lg-3">

                       <p>  
                            TALLUNT BOGHNI
                            <br>
                            4 rue Pasteur
                            <br>
                            75011 Paris
                            <br>
                            tel alg: +213 552 219 876
                            <br>
                            fax: +33 (0) 9 52 34 34 32
                       </p>


                        <p class="adresse_mail">
                           <a href="mailto:contact@alounasarchitecture.com" rel="nofollow">contact@alounasarchitecture.com</a>
                        </p>
                        </br>  
                     

        </div>


</div>
</div>





















<div class="row">


    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="col-md-11">
<form class="form-horizontal" action="." method="POST">
{% csrf_token %}


<div class="form-group  input-sm">
  <label for="nameField" class="col-xs-3 input-sm">Nom</label>
  <div class="col-xs-7">
     <input type="text" class="form-control input-sm" {% if form.nameField.value %} value="{{ form.nameField.value }}" {% endif %} id="id_nameField" name="nameField" id="nameField" placeholder="Entrer votre nom" />
  </div>
   


{% for error in form.nameField.errors %}  

   <p class="text-danger"> {{ error }} </p>

{% endfor %}  



</div>

<div class="form-group input-sm">
  <label for="nameField" class="col-xs-3 input-sm">Prénom</label>
    <div class="col-xs-7">
      <input type="text" class="form-control input-sm" {% if form.firstNameField.value %} value="{{ form.firstNameField.value }}" {% endif %} id="id_firstNameField" name="firstNameField" id="firstNameField" placeholder="Entrez votre prénom" />
    </div>
    



{% for error in form.firstNameField.errors %}  

   <p class="text-danger"> {{ error }} </p>

{% endfor %}  



</div>


<div class="form-group input-sm">
  <label for="emailField" class="col-xs-3 input-sm">Email</label>
    <div class="col-xs-7">
    
         <input type="email" class="form-control input-sm" {% if form.emailField.value %} value="{{ form.emailField.value }}" {% endif %} id="id_emailField" name="emailField" id="emailField" placeholder="Entrer votre Email" />
   
    
    </div>

   



{% for error in form.emailField.errors %}  

   <p class="text-danger"> {{ error }} </p>

{% endfor %}  


</div>

<div class="form-group input-sm">
  <label for="phoneField" class="col-xs-3 input-sm">Téléphone</label>
    <div class="col-xs-7">
      <input type="text" class="form-control input-sm" {% if form.phoneField.value %} value="{{ form.phoneField.value }}" {% endif %} id="id_phoneField" name="phoneField" id="phoneField" placeholder="Entrer votre numéro de téléphone" />
  </div>

 

{% for error in form.phoneField.errors %}  

   <p class="text-danger"> {{ error }} </p>

{% endfor %} 




</div>

<div class="form-group input-sm">
<label for="descField" class="col-xs-3 input-sm">Description</label>
<div class="col-xs-7">
<textarea class="form-control input-sm" {% if form.descField.value %} value="{{ form.descField.value }}" {% endif %} id="id_descField" name="descField" placeholder="Entrer un commentaire"></textarea>





</div>

{% for error in form.descField.errors %}  

   <p class="text-danger"> {{ error }} </p>

{% endfor %} 

</div>
<div class="col-xs-10 col-xs-offset-8 input-sm">
<button type="submit" class="btn btn-sm btn-primary">Envoyer </button> <button type="reset" class="btn btn-sm btn-default">Effacer</button>
</div>

</form>





</div>

</div>

</div>
{% include "footer.html" %}


{% endblock %}

website/templates/footer_profile.html
               
{% load staticfiles %}

                    <br>
  
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'theme.js' %}"></script>
    <script src="{% static 'jquery.isotope.min.js' %}"></script>



<div class="container-fluid footer-amar">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
         <a class="brand" href="https://fr.linkedin.com/in/asnounsamir" target="_blank">Powered by Samir ASNOUN</a>
    </div>
  </div>
</div>
                

website/templates/image_detail.html
{% extends "base.html" %}

{% load staticfiles %}




{% block content %}



<img src="{% static image.photo%}"/>




{% endblock %}

website/templates/index3 (copie).html
{% extends "base4.html" %} 

{% load staticfiles %}

{% block title %}Amar Lounas Architect{% endblock %}

{% block content %}

{% include "menu.html" %} 

    <div id="portfolio">
        <div class="container">



            <div class="row">
                <div class="col-md-12">
                    <div id="filters_container">
                        <ul id="filters">
                            <li><a href="#" data-filter="*" class="active">All</a></li>
                            <li class="separator">/</li>


                            {% for key, value in niveaux %}
                            <li><a href="#" data-filter=".{{key}}">{{value}}</a></li>
                            <li class="separator">/</li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>   


            <div class="row">
                <div class="col-md-12">
                    <div id="gallery_container">

            {% for image in images %}

                {% if image.get_chantier %}

                        <div class="photo {{image.get_chantier.get_niveau}} {{image.get_media.get_niveau}}">
                            <img src="{% static image.get__absolute_url %}" class="img-responsive" />
                            <a href="{{ image.get_chantier.get_absolute_url }}" class="mask">
                                <h3>{{image.get_chantier.title}}  </h3>
                                <small>{{image.get_chantier.get_niveau_v}}  </small>
                                <div class="more">+</div>
                            </a>
                        </div>

                {%endif%}

                {% if image.get_media %}


                        <div class="photo {{image.get_media.get_niveau}}  {{image.get_chantier.get_niveau}}">
                            <img src="{% static image.get__absolute_url %}" class="img-responsive" />
                            <a href="{{ image.get_media.get_absolute_url }}" class="mask">
                                <h3>{{image.get_media.title}} </h3>
                                <small>{{image.get_media.get_niveau_v}}</small>
                                <div class="more">+</div>
                            </a>
                        </div>

                {%endif%}
	        
            {% endfor %} 


                   </div>
                </div>
            </div>  

        </div>

    </div>

{% include "footer.html" %}

  
{% endblock %}

website/templates/index3.html
{% extends "base4.html" %} 

{% load staticfiles %}

{% block title %}Amar Lounas Architect{% endblock %}

{% block content %}

{% include "menu.html" %} 

    <div id="portfolio">
        <div class="container">



            <div class="row">
                <div class="col-md-12">
                    <div id="filters_container">
                        <ul id="filters">
                            <li><a href="#" data-filter="*" class="active">All</a></li>
                            <li class="separator">/</li>


                            {% for key, value in niveaux %}
                            <li><a href="#" data-filter=".{{key}}">{{value}}</a></li>
                            <li class="separator">/</li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>   


            <div class="row">
                <div class="col-md-12">
                    <div id="gallery_container">

            {% for image in images %}

                {% if image.get_chantier %}

                        <div class="photo {{image.get_chantier.get_niveau}} {{image.get_media.get_niveau}}">
                            <img src="{% static image.get__absolute_url %}" class="img-responsive" />
                            <a href="{{ image.get_chantier.get_absolute_url }}" class="mask">
                                <h3>{{image.get_chantier.title}}  </h3>
                                <small>{{image.get_chantier.get_niveau_v}}  </small>
                                <div class="more">+</div>
                            </a>
                        </div>

                {%endif%}

                {% if image.get_media %}


                        <div class="photo {{image.get_media.get_niveau}}  {{image.get_chantier.get_niveau}}">
                            <img src="{% static image.get__absolute_url %}" class="img-responsive" />
                            <a href="{{ image.get_media.get_absolute_url }}" class="mask">
                                <h3>{{image.get_media.title}} </h3>
                                <small>{{image.get_media.get_niveau_v}}</small>
                                <div class="more">+</div>
                            </a>
                        </div>

                {%endif%}
	        
            {% endfor %} 


                   </div>
                </div>
            </div>  

        </div>

    </div>

{% include "footer.html" %}

  
{% endblock %}

website/templates/index_ArtsArtisanat.html
{% extends "base2.html" %}

{% load staticfiles %}

{% block title %}Amar Lounas Architect{% endblock %}



{% block content %}
 
{% include "menu.html" %}

      <div class="row">
        <div class="col-md-11">
          {% for image in images_list %}
                    
                        <div class="view view-sixth">
                             
                             <img src="{% static image.get_thumb %}" class="img-thumbnail"  />
                             <div class="mask">
                                 <h2>{{ image.title }} </h2>
                                 <a href="{{ image.get_media.get_absolute_url }}" class="info">Read More</a>
                             </div>
                        </div> 

          {% endfor %} 

        </div>

      </div>


{% include "footer.html" %}
  
{% endblock %}

website/templates/items_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}



<h2>{{ item.name }}</h2>
 <p>{{ item.description }}</p>

<h3>Photos</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Thumbnail</th>
        <th>Caption</th>
    </tr>
    {% for photo in photos_list %}
    <tr>
        <td><i>{{ photo.title }}</i></td>
        <td>
            <a href="{{ photo.get_absolute_url }}">
                <img src="{% static  photo.thumb_url  %}" />
            </a>
        </td>
        <td>{{ photo.caption }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

website/templates/items_list.html
{% extends "base.html" %}

{% block title %}Item List{% endblock %}

{% block content %}

<p><a href="{% url index %}">&laquo; Back to main page</a></p>

<h2>Items</h2>
{% if object_list %}
<table>
    <tr>
        <th>Name</th>
        <th>Sample Thumb</th>
        <th>Description</th>
    </tr>
    {% for item in object_list %}
    <tr>
        <td><i>{{ item.name }}</i></td>
        <td>
            {% if item.photo_set.count %}
            <a href="{{ item.get_absolute_url }}">
                <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
            </a>
            {% else %}
            (No photos currently uploaded)
            {% endif %}
        </td>
        <td>{{ item.description }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>There are currently no items to display.</p>
{% endif %}

{% endblock %}

website/templates/menu.html
        <div class="row">



        <div class="col-xs-6 col-sm-6 col-md-4 col-lg-6 col-md-offset-4">


         <nav id="menu">
            <ul class="parent-menu">
               <li><a href="/profile/">Profil</a>
               </li>
               <li>
                  <a href="/projets/">Projects</a>

               </li>
               <li>
                  <a href="/artsetartisanats/">Arts et Artisanat</a>
               </li>
               <li>
                  <a href="/contact/">Contact</a>

               </li>
            </ul>
         </nav>



         </div>
         <div class="col-md-4"></div>

         </div>
         

website/templates/menu2.html
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
        
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/profil/" class="navbar-brand"><strong>Lounas Amar</strong></a>
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse" role="navigation">
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="/">Réalisations</a></li>
                    <li><a href="/profile/">Profil</a></li>                    
                    <li><a href="/contact/">Nous contacter</a></li>                    
                    <li><a href="sign-up.html">Sign up</a></li>
                    <li><a href="sign-in.html">Sign in</a></li>
                </ul>
            </div>
        </div>

</div>